name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"   # 每天运行
  workflow_dispatch:  # 允许手动触发工作流
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake game from contributions
        uses: Platane/snk@v2
        with:
          github_user_name: hahahahaha66  # 替换为你的 GitHub 用户名
          output: github-contribution-grid-snake.svg  # 输出到根目录

      - name: Commit and push Snake SVG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update Snake Game Contribution Grid" || exit 0
          git push
